services:

  python-docs:
    container_name: python-docs
    build:
      context: ./server
      dockerfile: ./Dockerfile-mkdocs
    restart: always
    ports:
      - "8000:8000"
    networks:
      - network-bridge

  fastapi-backend:
    container_name: fastapi-backend 
    build:
      context: ./server
      dockerfile: ./Dockerfile-fastapi
    restart: always
    # env_file:
    #   - ./server/.env
    ports:
      - "8080:8080"
    networks:
      - network-bridge

  streamlit-client:
    container_name: streamlit-client
    build:
      context: ./streamlit
      dockerfile: ./Dockerfile-streamlit
    restart: always
    # env_file:
    #   - ./server/.env
    ports:
      - "8501:8501"
    networks:
      - network-bridge


networks:
  network-bridge:
    driver: bridge
