site_name: Python-сервер документация

theme:
  name: "material"
  features:
    - navigation.expand

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: False
nav:
  - 'index.md'